In [1]:
import tensorflow as tf

print(tf.__version__)
print("TensorFlow is successfully imported and the version is:", tf.__version__)

2.18.0
TensorFlow is successfully imported and the version is: 2.18.0


In [2]:
x = tf.zeros([2, 3])
print(x)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


In [3]:
x = tf.eye(3)

In [4]:
x = tf.random.normal((3,3), mean=0, stddev=1)

print(x)

tf.Tensor(
[[ 0.9654587   0.05850933  0.11073846]
 [-1.3356526  -1.8284308  -2.0133467 ]
 [ 0.35157958 -0.9612697   1.4729317 ]], shape=(3, 3), dtype=float32)


In [6]:
x = tf.random.uniform([2, 3], minval=0, maxval=1)

print(x)

tf.Tensor(
[[0.20756245 0.1363908  0.02826905]
 [0.7328961  0.01219642 0.78584003]], shape=(2, 3), dtype=float32)


In [8]:
x = tf.range(start=0, limit=10, delta=2)

print(x)

tf.Tensor([0 2 4 6 8], shape=(5,), dtype=int32)


In [9]:
x = tf.cast(x, dtype=tf.float32)

print(x)

tf.Tensor([0. 2. 4. 6. 8.], shape=(5,), dtype=float32)


In [10]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = tf.add(x, y)
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [11]:
x = tf.constant([1,2,3])
y = tf.constant([4,5,6])

z = x + y
print(z)

tf.Tensor([5 7 9], shape=(3,), dtype=int32)


In [13]:
# Indexing



x = tf.constant([1,2,3,4,5,6,7,8,9,10])

print(x[:])

print(x[1:])

print(x[:6])

print(x[0])

tf.Tensor([ 1  2  3  4  5  6  7  8  9 10], shape=(10,), dtype=int32)
tf.Tensor([ 2  3  4  5  6  7  8  9 10], shape=(9,), dtype=int32)
tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [14]:
x = tf.constant([[1,2],[3,4],[5,6],[7,8],[9,10]])

print(x)

tf.Tensor(
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]], shape=(5, 2), dtype=int32)


In [16]:
x = tf.reshape(x, [2, 5])
print(x)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]], shape=(2, 5), dtype=int32)
